name: Static Analyze Reports

on:
  workflow_dispatch:

jobs:
  static_analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Upload the zip file
      - name: Upload static_analyze2.zip
        uses: actions/upload-artifact@v4
        with:
          name: static_analyze2.zip  # ✅ Artifact name
          path: static_analyze2.zip  # ✅ Actual file name

      # ✅ Download the zip artifact
      - name: Download static_analyze2.zip
        uses: actions/download-artifact@v4
        with:
          name: static_analyze2.zip  # ✅ Must match upload name
          path: artifacts

      # ✅ Unzip the downloaded file
      - name: Unzip static_analyze2.zip
        run: |
          mkdir -p extracted
          unzip artifacts/static_analyze2.zip -d extracted
          ls -R extracted

      # ✅ Find all report.xml files dynamically

      - name: Find report.xml files
        id: find_reports
        run: |
          files=$(find extracted -type f -name report.xml \
                  \( -path "*/linux/*" -o -path "*/qnx/*" -o -path "*/ubuntu/*" \))
          echo "REPORT_FILES<<EOF" >> $GITHUB_ENV
          echo "$files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # ✅ Upload the found report.xml files as artifact
      # Upload Linux report
      - name: Upload Linux report
        uses: actions/upload-artifact@v4
        with:
          name: linux-report
          path: extracted/**/linux/**/report.xml
      
      # Upload QNX report
      - name: Upload QNX report
        uses: actions/upload-artifact@v4
        with:
          name: qnx-report
          path: extracted/**/qnx/**/report.xml
      
      # Upload Ubuntu report
      - name: Upload Ubuntu report
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-report
          path: extracted/**/ubuntu/**/report.xml

