name: Static Analyze Reports

on:
  workflow_dispatch:

jobs:
  static_analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (1) Download the zip artifact
      - name: Download static_analyze2.zip
        uses: actions/download-artifact@v4
        with:
          name: static_analyze2.zip
          path: artifacts

      # (2) Unzip
      - name: Unzip static_analyze2.zip
        run: |
          mkdir -p extracted
          unzip artifacts/static_analyze2.zip -d extracted
          ls -R extracted

      # (3) Find all report.xml files dynamically
      - name: Find report.xml files
        id: find_reports
        run: |
          files=$(find extracted -type f -name report.xml \
                  \( -path "*/linux/*" -o -path "*/qnx/*" -o -path "*/ubuntu/*" \))
          echo "REPORT_FILES=$files" >> $GITHUB_ENV

      # (4) Upload the found report.xml files as artifact
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: report.xml
          path: ${{ env.REPORT_FILES }}
