name: Static Analyze Reports

on:
  workflow_dispatch:

jobs:
  static_analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List all files
        run: ls -R

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: report.xml
          path: |
            static_analyze/coding_rule/report/linux/report.xml
            static_analyze/coding_rule/report/qnx/report.xml
            static_analyze/coding_rule/report/ubuntu/report.xml
